=== brown-uk/corpus/data/disambig/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="text">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="sentence" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="token" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name = "value" type = "xs:string" use="required"/>
                                    <xs:attribute name = "lemma" type = "xs:string" use="required"/>
                                    <xs:attribute name = "tags" type = "xs:string" use="required"/>
                                    <xs:attribute name = "whitespaceBefore" type = "xs:string" />
                                    <xs:attribute name = "comment" type = "xs:string" />
                              </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="paragraph" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
  </xs:element> 
</xs:schema>

=== brown-uk/corpus/data/disambig/A_vikka_U_Cherkasakh_festyvalyly_sporstmeny_karatysty_2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<text xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../meta/schema.xsd">

<sentence>
  <token value="Бойове" lemma="бойовий" tags="adj:n:v_naz:compb" />
  <token value="мистецтво" lemma="мистецтво" tags="noun:inanim:n:v_naz" />
  <token value="в" lemma="в" tags="prep" />
  <token value="маси" lemma="маса" tags="noun:inanim:p:v_zna" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="У" lemma="у" tags="prep" />
  <token value="Черкасах" lemma="Черкаси" tags="noun:inanim:p:v_mis:ns:prop:geo" />
  <token value="фестивалили" lemma="фестивалити" tags="verb:imperf:past:p" />
  <token value="спортсмени-каратисти" lemma="спортсмен-каратист" tags="noun:anim:p:v_naz" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Такий" lemma="такий" tags="adj:m:v_zna:rinanim:pron:dem" />
  <token value="захід" lemma="захід" tags="noun:inanim:m:v_zna" />
  <token value="проводять" lemma="проводити" tags="verb:imperf:pres:p:3" />
  <token value="уперше" lemma="уперше" tags="adv" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Усе" lemma="усе" tags="noun:inanim:n:v_naz:pron:gen" />
  <token value="–" lemma="–" tags="punct" />
  <token value="аби" lemma="аби" tags="conj:subord" />
  <token value="привабити" lemma="привабити" tags="verb:perf:inf" />
  <token value="до" lemma="до" tags="prep" />
  <token value="бойових" lemma="бойовий" tags="adj:p:v_rod:compb" />
  <token value="мистецтв" lemma="мистецтво" tags="noun:inanim:p:v_rod" />
  <token value="молодь" lemma="молодь" tags="noun:inanim:f:v_zna" />
  <token value="та" lemma="та" tags="conj:coord" />
  <token value="заохотити" lemma="заохотити" tags="verb:perf:inf" />
  <token value="до" lemma="до" tags="prep" />
  <token value="спорту" lemma="спорт" tags="noun:inanim:m:v_rod" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Організували" lemma="організувати" tags="verb:perf:past:p" />
  <token value="захід" lemma="захід" tags="noun:inanim:m:v_zna" />
  <token value="обласний" lemma="обласний" tags="adj:m:v_naz" />
  <token value="центр" lemma="центр" tags="noun:inanim:m:v_naz:xp2" />
  <token value="«" lemma="«" tags="punct" />
  <token value="Спорт" lemma="спорт" tags="noun:inanim:m:v_naz" />
  <token value="для" lemma="для" tags="prep" />
  <token value="всіх" lemma="весь" tags="adj:p:v_rod:pron:gen" />
  <token value="»" lemma="»" tags="punct" />
  <token value="та" lemma="та" tags="conj:coord" />
  <token value="«" lemma="«" tags="punct" />
  <token value="Федерація" lemma="федерація" tags="noun:inanim:f:v_naz" />
  <token value="фунакоші" lemma="фунакоші" tags="noninfl:foreign" />
  <token value="шотокан" lemma="шотокан" tags="noninfl:foreign" />
  <token value="карате" lemma="карате" tags="noun:inanim:n:v_naz:nv" />
  <token value="України" lemma="Україна" tags="noun:inanim:f:v_rod:prop:geo" />
  <token value="»" lemma="»" tags="punct" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Показати" lemma="показати" tags="verb:perf:inf" />
  <token value="свої" lemma="свій" tags="adj:p:v_zna:rinanim:pron:pos" />
  <token value="уміння" lemma="уміння" tags="noun:inanim:p:v_zna" />
  <token value="зголосилося" lemma="зголоситися" tags="verb:rev:perf:past:n" />
  <token value="більше" lemma="більше" tags="adv:compc:predic" />
  <token value="півсотні" lemma="півсотні" tags="noun:inanim:p:v_rod:nv:alt" />
  <token value="спортсменів" lemma="спортсмен" tags="noun:anim:p:v_rod" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Усі" lemma="увесь" tags="adj:p:v_naz:pron:gen" />
  <token value="–" lemma="–" tags="punct" />
  <token value="вихованці" lemma="вихованець" tags="noun:anim:p:v_naz" />
  <token value="чотирьох" lemma="чотири" tags="numr:p:v_rod" />
  <token value="клубів" lemma="клуб" tags="noun:inanim:p:v_rod:xp2" />
  <token value="з" lemma="з" tags="prep" />
  <token value="Черкащини" lemma="Черкащина" tags="noun:inanim:f:v_rod:prop:geo" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Між" lemma="між" tags="prep" />
  <token value="собою" lemma="себе" tags="noun:unanim:s:v_oru:pron:refl" />
  <token value="змагалися" lemma="змагатися" tags="verb:rev:imperf:past:p" />
  <token value="за" lemma="за" tags="prep" />
  <token value="звання" lemma="звання" tags="noun:inanim:n:v_zna" />
  <token value="найсильнішого" lemma="найсильніший" tags="adj:m:v_rod:comps" />
  <token value="," lemma="," tags="punct" />
  <token value="а" lemma="а" tags="conj:coord" />
  <token value="для" lemma="для" tags="prep" />
  <token value="глядачів" lemma="глядач" tags="noun:anim:p:v_rod" />
  <token value="презентували" lemma="презентувати" tags="verb:perf:past:p" />
  <token value="ще" lemma="ще" tags="adv" />
  <token value="й" lemma="й" tags="part" />
  <token value="показові" lemma="показовий" tags="adj:p:v_zna:rinanim:compb" />
  <token value="виступи" lemma="виступ" tags="noun:inanim:p:v_zna" />
  <token value="." lemma="." tags="punct" />
</sentence>
<paragraph/>

<sentence>
  <token value="Анатолій" lemma="Анатолій" tags="noun:anim:m:v_naz:prop:fname" />
  <token value="Науменко" lemma="Науменко" tags="noun:anim:m:v_naz:prop:lname" />
  <token value="," lemma="," tags="punct" />
  <token value="президент" lemma="президент" tags="noun:anim:m:v_naz" />
  <token value="«" lemma="«" tags="punct" />
  <token value="Федерації" lemma="федерація" tags="noun:inanim:p:v_naz" />
  <token value="фунакоші" lemma="фунакіш" tags="noninfl:foreign" />
  <token value="шотокан" lemma="шотокан" tags="noninfl:foreign" />
  <token value="карате" lemma="карате" tags="noun:inanim:n:v_naz:nv" />
  <token value="України" lemma="Україна" tags="noun:inanim:f:v_rod:prop:geo" />
  <token value="»" lemma="»" tags="punct" />
  <token value=":" lemma=":" tags="punct" />
  <token value="«" lemma="«" tags="punct" />
  <token value="Важливим" lemma="важливий" tags="adj:n:v_oru:compb" />
  <token value="на" lemma="на" tags="prep" />
  <token value="сьогодні" lemma="сьогодні" tags="adv" />
  <token value="є" lemma="бути" tags="verb:imperf:pres:s:3" />
  <token value="заняття" lemma="заняття" tags="noun:inanim:n:v_naz" />
  <token value="масовим" lemma="масовий" tags="adj:m:v_oru:compb" />
  <token value="спортом" lemma="спорт" tags="noun:inanim:m:v_oru" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="От" lemma="от" tags="part" />
  <token value="якраз" lemma="якраз" tags="adv" />
  <token value="бойові" lemma="бойовий" tags="adj:p:v_naz:compb" />
  <token value="мистецтва" lemma="мистецтво" tags="noun:inanim:p:v_naz" />
  <token value="набирають" lemma="набирати" tags="verb:imperf:pres:p:3" />
  <token value="дуже" lemma="дуже" tags="adv:compb" />
  <token value="серйозні" lemma="серйозний" tags="adj:p:v_zna:rinanim:compb" />
  <token value="оберти" lemma="оберт" tags="noun:inanim:p:v_zna" />
  <token value="останнім" lemma="останній" tags="adj:m:v_oru:compb" />
  <token value="часом" lemma="час" tags="noun:inanim:m:v_oru" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="І" lemma="і" tags="conj:coord" />
  <token value="ми" lemma="ми" tags="noun:anim:p:v_naz:pron:pers:1" />
  <token value="бачимо" lemma="бачити" tags="verb:imperf:pres:p:1" />
  <token value="," lemma="," tags="punct" />
  <token value="справді" lemma="справді" tags="adv:insert" />
  <token value="," lemma="," tags="punct" />
  <token value="велику" lemma="великий" tags="adj:f:v_zna:compb" />
  <token value="армію" lemma="армія" tags="noun:inanim:f:v_zna" />
  <token value="прихильників" lemma="прихильник" tags="noun:anim:p:v_rod" />
  <token value="нашого" lemma="наш" tags="adj:m:v_rod:pron:pos" />
  <token value="виду" lemma="вид" tags="noun:inanim:m:v_rod" />
  <token value="спорту" lemma="спорт" tags="noun:inanim:m:v_rod" />
  <token value="»" lemma="»" tags="punct" />
  <token value="." lemma="." tags="punct" />
</sentence>

</text>

=== brown-uk/corpus/data/disambig/A_Ye_Melnyk_Na_Khmelnychchyni_zbyrayutsya_remontuvaty_try_problemni_mosty_2017.xml
<?xml version="1.0" encoding="UTF-8"?>
<text xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../meta/schema.xsd">

<sentence>
  <token value="Служба" lemma="служба" tags="noun:inanim:f:v_naz" />
  <token value="автомобільних" lemma="автомобільний" tags="adj:p:v_rod" />
  <token value="доріг" lemma="дорога" tags="noun:inanim:p:v_rod" />
  <token value="у" lemma="у" tags="prep" />
  <token value="Хмельницькій" lemma="хмельницький" tags="adj:f:v_mis" />
  <token value="області" lemma="область" tags="noun:inanim:f:v_mis" />
  <token value="планує" lemma="планувати" tags="verb:imperf:pres:s:3" />
  <token value="відремонтувати" lemma="відремонтувати" tags="verb:perf:inf" />
  <token value="три" lemma="три" tags="numr:p:v_zna" />
  <token value="мости" lemma="міст" tags="noun:inanim:p:v_zna" />
  <token value="у" lemma="у" tags="prep" />
  <token value="Дунаєвецькому" lemma="дунаєвецький" tags="adj:m:v_mis" />
  <token value="і" lemma="і" tags="conj:coord" />
  <token value="Полонському" lemma="полонський" tags="adj:m:v_mis" />
  <token value="районах" lemma="район" tags="noun:inanim:p:v_mis" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Про" lemma="про" tags="prep" />
  <token value="це" lemma="це" tags="noun:inanim:n:v_zna:pron:dem" />
  <token value="повідомляють" lemma="повідомляти" tags="verb:imperf:pres:p:3" />
  <token value="у" lemma="у" tags="prep" />
  <token value="прес-службі" lemma="прес-служба" tags="noun:inanim:f:v_mis:alt" />
  <token value="відомства" lemma="відомство" tags="noun:inanim:n:v_rod" />
  <token value="." lemma="." tags="punct" />
</sentence>
<paragraph/>

<sentence>
  <token value="Оголошення" lemma="оголошення" tags="noun:inanim:n:v_zna" />
  <token value="про" lemma="про" tags="prep" />
  <token value="проведення" lemma="проведення" tags="noun:inanim:n:v_zna" />
  <token value="відкритих" lemma="відкритий" tags="adj:p:v_rod:adjp:pasv:perf:compb" />
  <token value="торгів" lemma="торг" tags="noun:inanim:p:v_rod" />
  <token value="щодо" lemma="щодо" tags="prep" />
  <token value="закупівлі" lemma="закупівля" tags="noun:inanim:f:v_rod" />
  <token value="послуг" lemma="послуга" tags="noun:inanim:p:v_rod" />
  <token value="на" lemma="на" tags="prep" />
  <token value="проведення" lemma="проведення" tags="noun:inanim:n:v_zna" />
  <token value="аварійних" lemma="аварійний" tags="adj:p:v_rod:compb" />
  <token value="робіт" lemma="робота" tags="noun:inanim:p:v_rod" />
  <token value="із" lemma="із" tags="prep" />
  <token value="ліквідації" lemma="ліквідація" tags="noun:inanim:f:v_rod" />
  <token value="окремих" lemma="окремий" tags="adj:p:v_rod" />
  <token value="пошкоджень" lemma="пошкодження" tags="noun:inanim:p:v_rod" />
  <token value="елементів" lemma="елемент" tags="noun:inanim:p:v_rod" />
  <token value="мостів" lemma="міст" tags="noun:inanim:p:v_rod" />
  <token value="Служба" lemma="служба" tags="noun:inanim:f:v_naz" />
  <token value="автомобільних" lemma="автомобільний" tags="adj:p:v_rod" />
  <token value="доріг" lemma="дорога" tags="noun:inanim:p:v_rod" />
  <token value="у" lemma="у" tags="prep" />
  <token value="Хмельницькій" lemma="хмельницький" tags="adj:f:v_mis" />
  <token value="області" lemma="область" tags="noun:inanim:f:v_mis" />
  <token value="розмістила" lemma="розмістити" tags="verb:perf:past:f" />
  <token value="11" lemma="11" tags="number" />
  <token value="травня" lemma="травень" tags="noun:inanim:m:v_rod" />
  <token value="у" lemma="у" tags="prep" />
  <token value="системі" lemma="система" tags="noun:inanim:f:v_mis" />
  <token value="публічних" lemma="публічний" tags="adj:p:v_rod:compb" />
  <token value="закупівель" lemma="закупівля" tags="noun:inanim:p:v_rod" />
  <token value="«" lemma="«" tags="punct" />
  <token value="Prozorro" lemma="Prozorro" tags="unclass" />
  <token value="»" lemma="»" tags="punct" />
  <token value="." lemma="." tags="punct" />
</sentence>
<paragraph/>

<sentence>
  <token value="Відремонтувати" lemma="відремонтувати" tags="verb:perf:inf" />
  <token value="мають" lemma="мати" tags="verb:imperf:pres:p:3" />
  <token value="мости" lemma="міст" tags="noun:inanim:p:v_zna" />
  <token value="через" lemma="через" tags="prep" />
  <token value="річки" lemma="річка" tags="noun:inanim:p:v_zna" />
  <token value="Деревичка" lemma="Деревичка" tags="noun:inanim:f:v_naz:prop:geo" />
  <token value="і" lemma="і" tags="conj:coord" />
  <token value="Прислуч" lemma="Прислуч" tags="noun:inanim:f:v_naz:prop:geo" />
  <token value="у" lemma="у" tags="prep" />
  <token value="Полонському" lemma="полонський" tags="adj:m:v_mis" />
  <token value="районі" lemma="район" tags="noun:inanim:m:v_mis" />
  <token value="," lemma="," tags="punct" />
  <token value="та" lemma="та" tags="conj:coord" />
  <token value="Смотрич" lemma="Смотрич" tags="noun:inanim:m:v_zna:prop:geo" />
  <token value="у" lemma="у" tags="prep" />
  <token value="Дунаєвецькому" lemma="дунаєвецький" tags="adj:m:v_mis" />
  <token value="районі" lemma="район" tags="noun:inanim:m:v_mis" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Очікувана" lemma="очікуваний" tags="adj:f:v_naz:adjp:pasv:imperf:compb" />
  <token value="вартість" lemma="вартість" tags="noun:inanim:f:v_naz" />
  <token value="предметів" lemma="предмет" tags="noun:inanim:p:v_rod" />
  <token value="закупівель" lemma="закупівля" tags="noun:inanim:p:v_rod" />
  <token value="становить" lemma="становити" tags="verb:imperf:pres:s:3" />
  <token value=":" lemma=":" tags="punct" />
  <token value="625" lemma="625" tags="number" />
  <token value="тисяч" lemma="тисяча" tags="noun:inanim:p:v_rod:numr" />
  <token value="776" lemma="776" tags="number" />
  <token value="гривень" lemma="гривня" tags="noun:inanim:p:v_rod" />
  <token value="," lemma="," tags="punct" />
  <token value="1" lemma="1" tags="number" />
  <token value="мільйон" lemma="мільйон" tags="noun:inanim:m:v_zna:numr" />
  <token value="254" lemma="254" tags="number" />
  <token value="тисяч" lemma="тисяча" tags="noun:inanim:p:v_rod:numr:subst" comment="тисячі" />
  <token value="гривень" lemma="гривня" tags="noun:inanim:p:v_rod" />
  <token value="та" lemma="та" tags="conj:coord" />
  <token value="392" lemma="392" tags="number" />
  <token value="тисяч" lemma="тисяча" tags="noun:inanim:p:v_rod:numr:subst" comment="тисячі" />
  <token value="470" lemma="470" tags="number" />
  <token value="гривень" lemma="гривня" tags="noun:inanim:p:v_rod" />
  <token value="." lemma="." tags="punct" />
</sentence>
<sentence>
  <token value="Загальна" lemma="загальний" tags="adj:f:v_naz:compb" />
  <token value="вартість" lemma="вартість" tags="noun:inanim:f:v_naz" />
  <token value="–" lemma="–" tags="punct" />
  <token value="майже" lemma="майже" tags="adv" />
  <token value="2" lemma="2" tags="number" />
  <token value="мільйони" lemma="мільйон" tags="noun:inanim:p:v_naz:numr" />
  <token value="300" lemma="300" tags="number" />
  <token value="тисяч" lemma="тисяча" tags="noun:inanim:p:v_rod:numr" />
  <token value="гривень" lemma="гривня" tags="noun:inanim:p:v_rod" />
  <token value="." lemma="." tags="punct" />
</sentence>

</text>
